apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: project-monitoring-alertmanager
spec:
  containers:
  - name: alertmanager
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  - name: config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  initContainers:
  - name: init-config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  securityContext:
    fsGroup: 1000
    supplementalGroups:
    - 1000
