apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: project-monitoring-prometheus
spec:
  containers:
  - name: config-reloader
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsUser: 1000
      runAsGroup: 1000
  securityContext:
    fsGroup: 1000
    supplementalGroups:
    - 1000
